//
//  CatsListRouter.swift
//  TheCatsLibrary
//
//  Created by Mauro Coletes on 24/08/20.
//  Copyright (c) 2020 Mauro Coletes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CatsListRoutingLogic {
  func routeToCatDetail()
}

protocol CatsListDataPassing {
  var dataStore: CatsListDataStore? { get }
}

class CatsListRouter: NSObject, CatsListRoutingLogic, CatsListDataPassing {
  weak var viewController: CatsListViewController?
  var dataStore: CatsListDataStore?
  
  // MARK: Routing
  
    func routeToCatDetail() {
        guard let cat = dataStore?.cat else { return }
        let vc = CatsDetailViewController(viewModel: CatsDetailViewModel(cat: cat))
        
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
