//
//  CatsListPresenter.swift
//  TheCatsLibrary
//
//  Created by Mauro Coletes on 24/08/20.
//  Copyright (c) 2020 Mauro Coletes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatsListPresentationLogic {
    func presentLoading()
    func stopLoading()
    func presentCats(cats: [Cat])
}

class CatsListPresenter: CatsListPresentationLogic {
    
  weak var viewController: CatsListDisplayLogic?
  
    func presentLoading() {
        viewController?.startLoading()
    }
    
    func stopLoading() {
        viewController?.stopLoading()
    }
    
    func presentCats(cats: [Cat]) {
        var catsList: [CatsList.CatVM] = []
        for cat in cats {
            catsList.append(CatsList.CatVM(name: cat.name, description: cat.catDescription))
        }
        
        viewController?.showCats(cats: catsList)
    }
}
